### ISSUE TITLE
Submitting ‘install commit’ could lead to an error

### ISSUE THREAD

**Issue by jamesjwei** [csmserver/csmpe#29]
What happened is that condoor successfully submitted the ‘install commit’ command, but session log is not showing the command being submitted. The install action failed because it expects the command to return an install ID which is not happening. This problem went away after I manually deleted the condoor cache file in /tmp and restarted the CSM server.
2017-01-03 14:51:48,550     INFO: Dispatching: 'Install Commit Plugin'
2017-01-03 14:52:03,562    ERROR: [Install Commit Plugin] Operation ID not found.

**Comment by kstaniek** [comment]
This is the sunstone console problem.
